'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("dotNetTips.Utility.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BUTTON;LABEL.
        '''</summary>
        Friend ReadOnly Property ClearControlsToIgnore() As String
            Get
                Return ResourceManager.GetString("ClearControlsToIgnore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property Countries() As String
            Get
                Return ResourceManager.GetString("Countries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Regular expression string is null or empty!.
        '''</summary>
        Friend ReadOnly Property EXCEPTION_EMPTY_OR_NULL_REGEXP() As String
            Get
                Return ResourceManager.GetString("EXCEPTION_EMPTY_OR_NULL_REGEXP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Input string is null or empty!.
        '''</summary>
        Friend ReadOnly Property EXCEPTION_EMPTY_OR_NULL_STRING() As String
            Get
                Return ResourceManager.GetString("EXCEPTION_EMPTY_OR_NULL_STRING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exception Information Details:.
        '''</summary>
        Friend ReadOnly Property ExceptionDetails() As String
            Get
                Return ResourceManager.GetString("ExceptionDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HEADER.
        '''</summary>
        Friend ReadOnly Property ExceptionFormatterHeader() As String
            Get
                Return ResourceManager.GetString("ExceptionFormatterHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StackTrace Information Details:.
        '''</summary>
        Friend ReadOnly Property ExceptionStackTraceDetails() As String
            Get
                Return ResourceManager.GetString("ExceptionStackTraceDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exception Summary for:.
        '''</summary>
        Friend ReadOnly Property ExceptionSummary() As String
            Get
                Return ResourceManager.GetString("ExceptionSummary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exception Type.
        '''</summary>
        Friend ReadOnly Property ExceptionType() As String
            Get
                Return ResourceManager.GetString("ExceptionType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://ipinfodb.com/ip_query.php?ip={0}.
        '''</summary>
        Friend ReadOnly Property GeoLookup() As String
            Get
                Return ResourceManager.GetString("GeoLookup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to auth,password.
        '''</summary>
        Friend ReadOnly Property HttpHeadersToIgnore() As String
            Get
                Return ResourceManager.GetString("HttpHeadersToIgnore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inner Exception Information Details:.
        '''</summary>
        Friend ReadOnly Property InnerExceptionDetails() As String
            Get
                Return ResourceManager.GetString("InnerExceptionDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to read intrinsic property.  Error message: {0}.
        '''</summary>
        Friend ReadOnly Property IntrinsicPropertyError() As String
            Get
                Return ResourceManager.GetString("IntrinsicPropertyError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ======================================.
        '''</summary>
        Friend ReadOnly Property LineSeparator() As String
            Get
                Return ResourceManager.GetString("LineSeparator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Permission for UnmanagedCode is not available..
        '''</summary>
        Friend ReadOnly Property LogEntryIntrinsicPropertyNoUnmanagedCodePermissionError() As String
            Get
                Return ResourceManager.GetString("LogEntryIntrinsicPropertyNoUnmanagedCodePermissionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^((4\d{3})|(5[1-5]\d{2})|(6011))-?\d{4}-?\d{4}-?\d{4}|3[4,7]\d{13}$.
        '''</summary>
        Friend ReadOnly Property REGEXP_CREDIT_CARD() As String
            Get
                Return ResourceManager.GetString("REGEXP_CREDIT_CARD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^[a-zA-Z0-9\-\.]+\.(com|org|net|mil|edu|COM|ORG|NET|MIL|EDU)$.
        '''</summary>
        Friend ReadOnly Property REGEXP_DOMAIN() As String
            Get
                Return ResourceManager.GetString("REGEXP_DOMAIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*.
        '''</summary>
        Friend ReadOnly Property REGEXP_EMAIL() As String
            Get
                Return ResourceManager.GetString("REGEXP_EMAIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ([A-Z]:\\[^/:\*\?&lt;&gt;\|]+\.\w{2,6})|(\\{2}[^/:\*\?&lt;&gt;\|]+\.\w{2,6}).
        '''</summary>
        Friend ReadOnly Property REGEXP_FILE_PATH() As String
            Get
                Return ResourceManager.GetString("REGEXP_FILE_PATH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^(?n:(?&lt;lastname&gt;(St\.\ )?(?-i:[A-Z]\&apos;?\w+?\-?)+)(?&lt;suffix&gt;\ (?i:([JS]R)|((X(X{1,2})?)?((I((I{1,2})|V|X)?)|(V(I{0,3})))?)))?,((?&lt;prefix&gt;Dr|Prof|M(r?|(is)?)s)\ )?(?&lt;firstname&gt;(?-i:[A-Z]\&apos;?(\w+?|\.)\ ??){1,2})?(\ (?&lt;mname&gt;(?-i:[A-Z])(\&apos;?\w+?|\.))){0,2})$.
        '''</summary>
        Friend ReadOnly Property REGEXP_FIRST_LASTNAME() As String
            Get
                Return ResourceManager.GetString("REGEXP_FIRST_LASTNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ISBN(-1(?:(0)|3))?:?\x20+(?(1)(?(2)(?:(?=.{13}$)\d{1,5}([ -])\d{1,7}\3\d{1,6}\3(?:\d|x)$)|(?:(?=.{17}$)97(?:8|9)([ -])\d{1,5}\4\d{1,7}\4\d{1,6}\4\d$))|(?(.{13}$)(?:\d{1,5}([ -])\d{1,7}\5\d{1,6}\5(?:\d|x)$)|(?:(?=.{17}$)97(?:8|9)([ -])\d{1,5}\6\d{1,7}\6\d{1,6}\6\d$))).
        '''</summary>
        Friend ReadOnly Property REGEXP_ISBN() As String
            Get
                Return ResourceManager.GetString("REGEXP_ISBN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \b-?[1-9](?:\.\d+)?[Ee][-+]?\d+\b.
        '''</summary>
        Friend ReadOnly Property REGEXP_SCIENENTIFIC() As String
            Get
                Return ResourceManager.GetString("REGEXP_SCIENENTIFIC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^(\w|\W)+$.
        '''</summary>
        Friend ReadOnly Property REGEXP_STRING() As String
            Get
                Return ResourceManager.GetString("REGEXP_STRING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (\&lt;|\&gt;).
        '''</summary>
        Friend ReadOnly Property REGEXP_STRING_WEB_SAFE() As String
            Get
                Return ResourceManager.GetString("REGEXP_STRING_WEB_SAFE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ^(?n:(?!-[\d\,]*K) (?!-((\d{1,3},)*((([3-9]\d\d|2[89]\d|27[4-9])\xB0C)|(((4[6-9]|[5-9]\d)\d)\xB0F)))) -?\d{1,3}(,\d{3})*(\xB0[CF]|K) )$.
        '''</summary>
        Friend ReadOnly Property REGEXP_TEMP() As String
            Get
                Return ResourceManager.GetString("REGEXP_TEMP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (http|ftp|https):\/\/[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%&amp;amp;:/~\+#]*[\w\-\@?^=%&amp;amp;/~\+#])?.
        '''</summary>
        Friend ReadOnly Property REGEXP_URL() As String
            Get
                Return ResourceManager.GetString("REGEXP_URL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ((\(\d{3}\) ?)|(\d{3}-))?\d{3}-\d{4}.
        '''</summary>
        Friend ReadOnly Property REGEXP_US_PHONE_NUMBER() As String
            Get
                Return ResourceManager.GetString("REGEXP_US_PHONE_NUMBER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \d{3}-\d{2}-\d{4}.
        '''</summary>
        Friend ReadOnly Property REGEXP_US_SSN() As String
            Get
                Return ResourceManager.GetString("REGEXP_US_SSN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \d{5}(-\d{4})?.
        '''</summary>
        Friend ReadOnly Property REGEXP_US_ZIP_CODE() As String
            Get
                Return ResourceManager.GetString("REGEXP_US_ZIP_CODE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;states&gt;
        '''	&lt;state name=&quot;ALABAMA&quot; abbreviation=&quot;AL&quot; /&gt;
        '''	&lt;state name=&quot;ALASKA&quot; abbreviation=&quot;AK&quot; /&gt;
        '''	&lt;state name=&quot;AMERICAN SAMOA&quot; abbreviation=&quot;AS&quot; /&gt;
        '''	&lt;state name=&quot;ARIZONA&quot; abbreviation=&quot;AZ&quot; /&gt;
        '''	&lt;state name=&quot;ARKANSAS&quot; abbreviation=&quot;AR&quot; /&gt;
        '''	&lt;state name=&quot;CALIFORNIA&quot; abbreviation=&quot;CA&quot; /&gt;
        '''	&lt;state name=&quot;COLORADO&quot; abbreviation=&quot;CO&quot; /&gt;
        '''	&lt;state name=&quot;CONNECTICUT&quot; abbreviation=&quot;CT&quot; /&gt;
        '''	&lt;state name=&quot;DELAWARE&quot; abbreviation=&quot;DE&quot; /&gt;
        '''	&lt;state name=&quot;DISTRICT OF COLUMBIA&quot; abbr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property States() As String
            Get
                Return ResourceManager.GetString("States", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 00.
        '''</summary>
        Friend ReadOnly Property TabIndexFormat() As String
            Get
                Return ResourceManager.GetString("TabIndexFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}.{1}.
        '''</summary>
        Friend ReadOnly Property TabIndexFormatValue() As String
            Get
                Return ResourceManager.GetString("TabIndexFormatValue", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
